services:
  redis:
    build:
      context: ./redis-service
      dockerfile: Dockerfile
    ports:
      - "6379:6379"
   
  db:
    build: 
      context: ./db-service
      dockerfile: Dockerfile
    ports:
      - "5432:5432"

  vote-service:
    build:
      context: ./vote-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - redis
  
  worker-service:
    build:
      context: ./worker-service
      dockerfile: Dockerfile
    depends_on:
      - redis
      - db
  result-service:
    build:
      context: ./result-service
      dockerfile: Dockerfile
    ports:
      - "5001:4000"
    depends_on:
      - db
volumes:
  postgres_data: